__all__ = [
    "POSButton",
    "POSFrame"
]

from enum import Enum


class POSFrame(Enum):
    ASK_DRAWER_COUNT_CASH = "ask-drawer-count-cash"
    ASK_DRAWER_COUNT_CORRECT = "ask-drawer-count-correct"
    ASK_TENDER_STARTING_COUNTS = "ask-tender-for-starting-counts"
    ASK_TENDER_ENDING_COUNTS = "ask-tender-for-ending-counts"
    ASK_TENDER_AMOUNT_CASH = "ask-tender-amount-cash"
    ASK_TENDER_AMOUNT_CREDIT = "ask-tender-amount-credit"
    ASK_TENDER_AMOUNT_DEBIT = "ask-tender-amount-debit"
    ASK_TENDER_AMOUNT_CHECK = "ask-tender-amount-check"
    ASK_TENDER_AMOUNT_GIFT_CERTIFICATE = "ask-tender-amount-type-5"
    ASK_TENDER_AMOUNT_MANUAL_IMPRINT = "ask-tender-amount-type-9"
    ASK_TENDER_AMOUNT_FOOD_STAMPS = "ask-tender-amount-type-8"
    ASK_TENDER_AMOUNT_FOREIGN = "ask-tender-amount-type-102"
    ASK_TENDER_AMOUNT_MFC = "ask-tender-amount-type-21"
    ASK_ENTER_DOLLAR_AMOUNT = "ask-enter-dollar-amount"
    ASK_SAFE_DROP_AMOUNT_CASH = "ask-safe-drop-amount-cash"
    ASK_OPERATOR_PIN = "ask-operator-pin"
    ASK_EXTERNAL_QUESTION = "ask-external-yes-no-question"
    ASK_BARCODE_SCAN = "ask-barcode-scan"
    ASK_CHECK_TRANSIT_NUMBER = "ask-check-transit-number"
    ASK_CHECK_ACCOUNT_NUMBER = "ask-check-account-number"
    ASK_CHECK_SEQUENCE_NUMBER = "ask-check-sequence-number"
    ASK_ECHECK_AGREEMENT = "ask-echeck-agreement"
    MAIN = "main-frame"
    RECEIPT = "receipt-frame"
    RECALL_TRANSACTION_LIST_FRAME = "recall-transaction-list-frame"
    SCROLL_PREVIOUS_FRAME = "scroll-previous-frame"
    MSG_OPERATOR_NOT_FOUND = "show-message-1002"
    MSG_OPERATOR_NOT_OPENED = "show-message-1003"
    MSG_TOO_FEW_CHARS = "show-message-300"
    START_SHIFT = "start-shift"
    OTHER_FUNCTIONS = "other-functions"
    TERMINAL_LOCK = "terminal-lock"
    ASK_FINALIZE_ZERO_TRANSACTION = "ask-finalize-zero-amount"
    ASK_CONFIRM_MANUFACTURER_COUPON = "ask-confirm-manufacturer-coupon"
    ASK_CONFIRM_REFUND = "ask-confirm-refund"
    ASK_CARD_SWIPE_FOR_SIGMA = "ask-card-swipe-for-sigma"
    ASK_COUPONS_EXPIRATION_DATE_ACCEPTABLE = "ask-coupons-expiration-date-acceptable"
    ASK_ACCEPT_AMOUNT_WILL_BE_RESTRICTED = "amount-too-large-ask-accept-amount-will-be-restricted"
    MSG_TRANSACTION_CANCEL_NOT_ALLOWED = "show-message-1520"
    MSG_ZERO_QUANTITY_NOT_ALLOWED = "show-message-1527"
    MSG_ITEM_LOCKED = "show-message-1501"
    MSG_ITEM_NOT_FOUND = "show-message-1502"
    MSG_NO_ITEM_TO_VOID = "show-message-1506"
    MSG_QUANTITY_NOT_ALLOWED = "show-message-1512"
    MSG_QUANTITY_TOO_LARGE = "show-message-1516"
    MSG_CANCEL_NOT_ALLOWED = "show-message-501"
    MSG_REFUND_NOT_ALLOWED = "show-message-505"
    MSG_NOT_ALLOWED_AFTER_TOTAL = "show-message-3441"
    MSG_COUPON_AMOUNT_TOO_LARGE = "show-message-1571"
    MSG_COUPON_REQUIREMENTS_NOT_MET = "show-message-1573"
    MSG_COUPON_EXPIRED = "show-message-1574"
    MSG_COUPONS_NOT_ALLOWED = "show-message-1575"
    MSG_AGE_REQUIREMENTS_NOT_MET = "show-message-1557"
    MSG_INPUT_OUT_OF_RANGE = "show-message-101"
    MSG_AMOUNT_TOO_LARGE = "show-message-3002"
    MSG_AMOUNT_TOO_SMALL = "show-message-3015"
    MSG_NO_AMOUNT_ENTERED = "show-message-3011"
    MSG_TENDER_NOT_ALLOWED = "show-message-3043"
    MSG_TENDER_NOT_ALLOWED_NON_FUEL = "show-message-3008"
    MSG_PARTIAL_TENDER_NOT_ALLOWED = "show-message-3009"
    MSG_PARTIAL_TENDER_NOT_ALLOWED_PUMP_TEST = "show-message-3069"
    MSG_PREPAY_NOT_ALLOWED = "show-message-3013"
    MSG_NO_TRAN_IN_PROGRESS = "show-message-3505"
    MSG_AGE_REQUIREMENTS_NOT_MET_EFFECTIVE = "show-message-7754"
    MSG_CREDIT_OUT_OF_ORDER = "show-message-3554"
    MSG_NO_ITEM_TO_ADD = "show-message-3549"
    MSG_LOCK_WHILE_TRAN_IN_PROGRESS = "show-message-6002"
    MSG_INCORRECT_LOCKING_OPERATOR = "show-message-6000"
    MSG_SECURITY_DENIED = "show-message-2005"
    MSG_SWIPE_AHEAD = "show-message-0"
    MSG_PINPAD_REBOOT_IN_5_MINUTES = "show-message-8040"
    MSG_PINPAD_REBOOT_IN_MINUTE = "show-message-8041"
    MSG_PINPAD_REBOOTING = "show-message-8042"
    MSG_OTHER = "show-message-other"
    MSG_PUMP_AUTH_FAILED_REFUND_CUSTOMER = "show-message-3576"
    MSG_PUMP_AUTH_FAILED_CUSTOMER_REFUNDED = "show-message-3588"
    MSG_CARD_ACTIVATION_SUCCESSFUL = "show-message-8011"
    MSG_CARD_DEACTIVATION_SUCCESSFUL = "show-message-8024"
    ASK_VERIFY_AGE = "ask-verify-age"
    ASK_VERIFY_AGE_JUUL = "ask-verify-age-juul"
    ASK_VERIFY_AGE_OVER_UNDER = "ask-verify-age-over-under"
    ASK_VERIFY_AGE_MANUAL = "ask-verify-age-manual"
    ASK_VERIFY_AGE_NO_MANUAL = "ask-verify-age-no-manual"
    ASK_BARCODE_ENTRY = "ask-barcode-entry"
    ASK_MANUAL_CARD_ENTRY = "ask-manual-card-entry"
    ENTER_QUANTITY_AMOUNT = "enter-quantity-amount"
    PRICE_CHECK_FRAME = "price-check-frame"
    PRICE_OVERRIDE_FRAME = "price-override-frame"
    ASK_FOR_A_REASON = "ask-for-a-reason"
    ASK_VALIDATE_ID = "ask-validate-id"
    MSG_ITEM_COUNT_EXCEEDS_MAXIMUM = "show-message-1515"
    MSG_VERIFIED_AGE_LOWERED = "show-message-1640"
    MSG_RECALL_ITEMS_REMOVED = "show-message-1644"
    MSG_STORE_TRAN_NOT_ALLOWED = "show-message-3516"
    GRADE_SELECTION = "ask-fuel-grade-select"
    PREPAY_AMOUNT = "ask-for-prepay-amount"
    ASK_PAID_IN_AMOUNT_PREFIX = "ask-paid-in-amount-"
    ASK_PAID_OUT_AMOUNT_PREFIX = "ask-paid-out-amount-"
    ASK_REASON_AND_TENDER = "ask-reason-and-tender"
    SELECT_REFUND_TENDER = "select-refund-tender"
    SELECT_SAFE_DROP_TENDER = "select-safe-drop-tender"
    ASK_CONFIRM_LOCK_TERMINAL = "ask-confirm-lock-terminal"
    ASK_SECURITY_OVERRIDE = "ask-security-override"
    CONTAINER_DEPOSIT_REDEMPTION_FRAME = "container-deposit-redemption-frame"
    SELECT_DEPARTMENT_SALE = "select-department-sale"
    TANK_INVENTORY_LEVELS = "tank-inventory-levels"
    ASK_CONFIRM_DRIVE_OFF = "ask-confirm-drive-off"
    SELECT_TENDER = "select-tender"
    SELECT_TENDER_FROM_GROUP = "select-tender-from-group"
    ASK_CONFIRM_PUMP_TEST = "ask-confirm-pump-test"
    VERSION_INFO = "version-info"
    ASK_CONFIRM_USER_OVERRIDE = "ask-confirm-user-override"
    CREDIT_GET_CARD_SWIPE = "credit-get-card-swip"
    ASK_SVC_ACTIVATION_AMOUNT = "ask-svc-activation-amount"
    SCROLL_PREVIOUS = "scroll-previous-frame"
    WAIT_CUSTOMER_CONFIRMATION = "wait-customer-confirmation"
    ASK_CANCEL_REST_IN_GAS = "ask-cancel-rest-in-gas"
    MSG_ADDITIONAL_LOYALTY_NOT_ALLOWED = "show-message-3442"

    WAIT_PES_PROCESSING = "wait-pes-processing"

    WAIT_CREDIT_PROCESSING = "wait-credit-processing"
    CREDIT_PROCESSING_DECLINED = "credit-abort"
    ASK_AMOUNT_CONFIRMATION = "ask-amount-confirmation"

    ASK_SELL_CARWASH_WITHOUT_CODE = "ask-sell-carwash-without-code"
    ASK_CARWASH_SALE_SELECT = "ask-carwash-sale-select"
    ASK_CANCEL_CARWASH_RETRY = "ask-cancel-carwash-retry"
    WAIT_CARWASH_PROCESSING = "wait-carwash-communication-in-progress"
    ASK_LOTTERY_PRIZE_TYPE = "ask-lottery-prize-type"
    ASK_LOTTERY_SALE_SELECT = "ask-lottery-sale-select"
    ASK_LOTTERY_REDEMPTION_SELECT = "ask-lottery-redemption-select"
    ASK_ENTER_LOTTERY_AMOUNT = "ask-enter-lottery-amount"
    ASK_VOID_MULTIPLE_TRANSACTIONS = "ask-void-multiple-transactions"
    ASK_ALTERNATE_ID = "ask-alternate-id"

    SELECT_COUPON = "select-coupon"
    SELECT_DISCOUNT = "select-discount"
    ASK_COUPON_PERCENT = "ask-coupon-percent"
    COUPON_ALREADY_ADDED = "show-message-1587"
    ASK_COUPON_AMOUNT = "ask-coupon-amount"

    MSG_LMOP_RESTRICTED = "show-message-17505"
    TENDER_NOT_ALLOWED_FOR_ALL_ITEMS_ASK_ACCEPT_AMOUNT_WILL_BE_RESTRICTED = "tender-not-allowed-for-all-items-ask-accept-amount-will-be-restricted"
    WAIT_WINCOR_PROCESSING = "wait-wincor-processing"
    LAST_CHANCE_LOYALTY = "wait-loyalty-processing"
    ASK_ITEM_WEIGHT = "ask-item-weight"
    MSG_PRICE_OVERRIDE_NOT_ALLOWED = "show-message-1548"
    MSG_TENDER_NOT_ALLOWED_FOR_NON_FUEL_ITEMS = "show-message-3008"
    ASK_LOYALTY_CARD = "ask-loyalty-card"
    YES_NO_PROMPT = "yes-no-prompt"
    ASK_CONFIRM_PES_DISCOUNT = "ask-confirm-pes-discount"
    ASK_ENTER_LOYALTY_PIN = "ask-enter-loyalty-pin"
    NUMERIC_PROMPT = "numeric-prompt"
    ASK_CONFIRM_DESTINATION = "ask-confirm-destination"

class POSButton(Enum):
    KEY_1 = "key-1"
    KEY_2 = "key-2"
    KEY_3 = "key-3"
    KEY_4 = "key-4"
    KEY_5 = "key-5"
    KEY_6 = "key-6"
    KEY_7 = "key-7"
    KEY_8 = "key-8"
    KEY_9 = "key-9"
    KEY_0 = "key-0"
    KEY_00 = "key-00"

    QNT_01 = "qnt-01"
    QNT_02 = "qnt-02"
    QNT_03 = "qnt-03"
    QNT_04 = "qnt-04"
    QNT_05 = "qnt-05"
    QNT_06 = "qnt-06"
    QNT_07 = "qnt-07"
    QNT_08 = "qnt-08"
    QNT_09 = "qnt-09"
    QNT_10 = "qnt-10"

    ENTER = "enter"
    CLEAR = "clear"
    BACKSPACE = "backspace"
    GO_BACK = "go-back"
    YES = "yes"
    NO = "no"
    DONE = "done"
    OVER = "over"
    UNDER = "under"
    CANCEL = "cancel"
    CONTINUE = "continue"
    LOTTERY_CASH = "cash"
    LOTTERY_TICKET = "ticket"

    LOTTERY_SALE = "sell-lotery"
    LOTTERY_REDEMPTION = "redeem-lotery"
    SELL_BC_PREFIX = "sell-bc-"
    DEPARTMENT_SALE = "department-sale"
    SVC_ACTIVATION = "sell-bc-444666"
    SELL_CARWASH = "sell-carwash"

    SHIFT = "shift"
    UNLOCK = "unlock"

    TENDER_CASH = "tender-cash-70000000023"
    TENDER_CREDIT = "tender-credit-70000000025"
    TENDER_DEBIT = "tender-debit-70000000026"
    TENDER_CHECK = "tender-check-70000000024"
    TENDER_GIFT_CERTIFICATE = "tender-type-5-70000000034"
    TENDER_MANUAL_IMPRINT = "tender-type-9-70000000036"
    TENDER_FOOD_STAMPS = "tender-type-8-70000000032"
    TENDER_FOREIGN_PREFIX = "tender-type-102-"
    TENDER_MFC_PREFIX = "tender-type-21-"
    TENDER_GROUP_PREFIX = "tender-group-"
    MORE = "more"

    TENDER_CASH_NO_EXTERNAL_ID = "tender-cash"
    TENDER_CREDIT_NO_EXTERNAL_ID = "tender-credit"
    TENDER_DEBIT_NO_EXTERNAL_ID = "tender-debit"
    TENDER_CHECK_NO_EXTERNAL_ID = "tender-check"
    TENDER_GIFT_CERTIFICATE_NO_EXTERNAL_ID = "tender-type-5"
    TENDER_MANUAL_IMPRINT_NO_EXTERNAL_ID = "tender-type-9"
    TENDER_FOOD_STAMPS_NO_EXTERNAL_ID = "tender-type-8"

    PRESET_5 = "preset-5"
    PRESET_10 = "preset-10"
    PRESET_20 = "preset-20"
    EXACT_DOLLAR = "exact-dollar"
    NEXT_DOLLAR = "next-dollar"
    CHARITY_DONATION = "charity-donation"

    END_SHIFT = "end-shift"
    LOCK = "lock-out"

    OTHER_FUNCTIONS = "other-functions"
    ENTER_PLU_UPC = "enter-plu/upc"
    PRICE_CHECK = "price-check"
    CHANGE_QUANTITY = "change-quantity"
    VOID_ITEM = "void-item"
    VOID_RECEIPT = "void-receipt"
    PRICE_OVERRIDE = "price-override"
    PRINT_RECEIPT = "print-receipt"
    RECEIPT_DOWN = "rcpt-scrolldown"
    RECEIPT_UP = "rcpt-scrollup"

    SCROLL_PREVIOUS = "scroll-prev-transaction"
    STORE_TRANSACTION = "store-transaction"
    RECALL_TRANSACTION = "recall-transaction"
    REFUND = "refund"
    DRIVE_OFF = "drive-off"
    PUMP_TEST = "pump-test"
    VERSION_INFO = "version-info"
    SHOW_BUSINESS_DAY = "current-business-day"
    COUPON_LOOKUP = "coupon-lookup"
    DISCOUNT_LOOKUP = "discount-lookup"
    LOYALTY_BALANCE_INQUIRY = "loyalty-balance-inquiry"
    ALTERNATE_ID_LOYALTY = "alternate-id-loyalty"
    IDENTIFY_EMPLOYEE = "identify-employee"
    PDI_INSTANT_LOTTERY_TX = "pdi-instant-lottery-tx"
    PDI_MACHINE_LOTTERY_TX = "pdi-machine-lottery-tx"
    CONTAINER_DEPOSIT_REDEMPTION = "redeem-container-deposit"

    MANUAL_ENTER = "manual-enter"
    ADD_TO_ORDER = "add-to-order"
    ENTER_CARD = "enter-card"

    MANUAL_ENTER_BARCODE = "manual-enter-bar-cod"

    INSTANT_APPROVAL = "instant-approval"
    MILITARY_ID = "military-id"
    MANUAL_ENTRY = "manual-entry"

    PREPAY_CANCEL_PREPAY = "prepay-cancel-prepay"
    REST_IN_GAS = "rest-in-gas"
    GRADE_PREMIUM = "Premium"
    GRADE_REGULAR = "Regular"
    GRADE_DIESEL = "Diesel"
    GRADE_MIDGRADE = "Midgrade"

    PUMP_START_STOP = "start-stop"
    PAY_FIRST = "pay1"
    PAY_SECOND = "pay2"
    REFUND_FIRST = "pay1"
    REFUND_SECOND = "pay2"

    DOWN_ARROW = "down-arrow"
    UP_ARROW = "up-arrow"

    REFUND_FUEL = "refund-fuel"
    RELATED_PREPAY = "related-prepay"
    FUEL_RECEIPT = "fuel-receipt"